# Generated by Django 5.1.6 on 2025-03-23 04:34

import django.contrib.auth.base_user
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSites',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(upload_to=main.models.user_profile_pic_path)),
                ('city_or_municipality', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('innovator', 'Innovator'), ('contributor', 'Contributor'), ('collector', 'Collector'), ('guest', 'Guest')], default='contributor', max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('subdivision', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_sites', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_sites_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.contrib.auth.base_user.BaseUserManager),
        ),
    ]
