# Generated by Django 5.1.6 on 2025-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUsersites',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField()),
                ('profile_picture', models.CharField(max_length=100)),
                ('city_or_municipality', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('subdivision', models.CharField(max_length=50)),
                ('is_superuser', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'main_usersites',
                'managed': False,
            },
        ),
    ]
