# Generated by Django 5.1.6 on 2025-03-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainusersites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainUsersites',
        ),
    ]
