# Generated by Django 5.1.6 on 2025-03-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_remove_usersites_is_active_remove_usersites_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersites',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersites',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_sites', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersites',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_sites_permissions', to='auth.permission'),
        ),
    ]
