# Generated by Django 5.1.6 on 2025-03-24 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usersites_is_active_usersites_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=530)),
                ('title', models.CharField(max_length=120)),
                ('share_url', models.CharField(blank=True, max_length=250, null=True)),
                ('user_role_type', models.CharField(max_length=50)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
