# Generated by Django 5.1.6 on 2025-03-24 05:23

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='id',
            new_name='ID',
        ),
        migrations.CreateModel(
            name='UserPost_BLOB',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('blob', models.ImageField(upload_to=main.models.user_post_blob_path)),
                ('position', models.IntegerField()),
                ('USER_POST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpost')),
            ],
        ),
    ]
