# Generated by Django 5.1.6 on 2025-04-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_id_userpost_id_userpost_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('USER_RECIPIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('USER_SENDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
                ('blob', models.ImageField(blank=True, null=True, upload_to='')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('USERS_MESSAGES_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usermessages')),
            ],
        ),
    ]
