# Generated by Django 5.1.6 on 2025-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_friendships'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=20),
        ),
    ]
