# Generated by Django 5.1.6 on 2025-06-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usermessages_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='message_text',
            field=models.TextField(null=True),
        ),
    ]
