# Generated by Django 5.1.6 on 2025-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_usermessages_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
