# Generated by Django 5.1.6 on 2025-06-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_usermessages_message_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
