# Generated by Django 5.1.6 on 2025-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen'), ('request', 'Request')], default='sent', max_length=20),
        ),
    ]
