# Generated by Django 5.1.6 on 2025-06-30 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_usermessages_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=False)),
                ('POST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpost_blob')),
                ('USER_ACCEPT_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
