# Generated by Django 5.1.6 on 2025-07-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_taskrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskRequest',
        ),
    ]
