# Generated by Django 5.1.6 on 2025-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_taskrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
