# Generated by Django 5.1.6 on 2025-07-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_taskrequest_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='POST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpost'),
        ),
    ]
