# Generated by Django 5.1.6 on 2025-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_taskrequest_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskRequest',
        ),
    ]
