# Generated by Django 5.1.6 on 2025-07-14 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_taskrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('POST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpost')),
                ('USER_ACCEPT_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullfill_request_user', to=settings.AUTH_USER_MODEL)),
                ('USER_FULLFILL_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
