# Generated by Django 5.1.6 on 2025-07-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_taskrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrequest',
            old_name='USER_ACCEPT_REQUEST',
            new_name='USER_RECIEVE_REQUEST',
        ),
    ]
