# Generated by Django 5.1.6 on 2025-07-22 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_user_accept_request_taskrequest_user_recieve_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen'), ('request', 'Request'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='sent', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('stars', models.IntegerField()),
                ('comment', models.TextField()),
                ('USER_FULLFILL_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_review_user', to=settings.AUTH_USER_MODEL)),
                ('USER_RECIEVE_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullfill_review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
