# Generated by Django 5.1.6 on 2025-08-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_usermessages_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersites',
            name='role',
            field=models.CharField(choices=[('innovator', 'Innovator'), ('contributor', 'Contributor'), ('collector', 'Collector'), ('guest', 'Guest'), ('showcase', 'Showcase')], default='contributor', max_length=20),
        ),
    ]
