# Generated by Django 5.1.6 on 2025-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_usersites_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
