# Generated by Django 5.1.6 on 2025-08-15 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('request', 'Request'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('messaged', 'Messaged')], max_length=20)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('viewed', 'Viewed')], default='delivered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('USER_NOTIFY_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notify_owner', to=settings.AUTH_USER_MODEL)),
                ('USER_NOTIFY_TRIGGER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notify_trigger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
