# Generated by Django 5.1.6 on 2025-08-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request', 'Request'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('messaged', 'Messaged'), ('add_friend', 'Add_friend'), ('accept_friend', 'Accept_friend')], max_length=20),
        ),
    ]
