# Generated by Django 5.1.6 on 2025-08-25 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FogotPasswordFixed',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_password_change', models.TextField()),
                ('REFENCE_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
