# Generated by Django 5.1.6 on 2025-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_fogotpasswordfixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_msg', models.TextField()),
                ('rate', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
